### ISSUE TITLE
你好，我想要在本地获取了新增消息（也就是无响应器）然后直接发送给指定用户要怎么操作呢？请问在哪里可以找到完整的函数文档？

### ISSUE THREAD

**Issue by mingxuan-li-official** [he0119/nonebot2-cookbook#1]
我想要在本地获取了新增消息（也就是无响应器）然后直接发送给指定用户要怎么操作呢？请问在哪里可以找到完整的函数文档？

**Comment by he0119** [comment]
> 我想要在本地获取了新增消息（也就是无响应器）

这是什么意思？收到消息事件之后转发给指定用户吗？

**Comment by mingxuan-li-official** [comment]
对，就是从别处获取信息转发给用户，这个要怎么操作呢？我现在只懂得响应后再执行，但是找不到更多相关内容

**Comment by mingxuan-li-official** [comment]
不是消息时间，准确的说是监听本地的txt文件，然后将更新内容转发给指定用户，目前监听已经实现了，但是写成插件转发一直不行，希望大佬指点

**Comment by syytt1** [comment]
`from pathlib import Path

import nonebot
from nonebot import get_driver
from nonebot.plugin import PluginMetadata
from nonebot.typing import T_State

from .config import Config
import os
import time
from nonebot import get_bot

__plugin_meta__ = PluginMetadata(
    name="first",
    description="发送通知给管理员",
    usage="学生端->管理员",
    config=Config,
)

global_config = get_driver().config
config = Config.parse_obj(global_config)

sub_plugins = nonebot.load_plugins(
    str(Path(__file__).parent.joinpath("plugins").resolve())
)

@nonebot.on_startup
async def startup_handler():
    filename =  ''# 指定要读取的文本文件名
    qq_number = ''  # 指定要发送的QQ号

    # 获取文件的初始大小
    file_size = os.path.getsize(filename)

    while True:
        current_size = os.path.getsize(filename)

        if current_size > file_size:  # 文件有新增内容
            with open(filename, 'r', encoding='utf-8') as file:
                file.seek(file_size)  # 将文件指针定位到上次读取的位置
                new_content = file.read()  # 读取新增的内容
                #print("新增内容为:")
                #print(new_content)

            bot = get_bot()
            await bot.call_api('send_private_msg', user_id=qq_number, message=new_content)

            file_size = current_size  # 更新文件大小

        time.sleep(1)  # 每秒检查一次文件是否有新增内容

@nonebot.on_shutdown
async def shutdown_handler():
    # 在插件关闭时执行清理操作
    pass
`

**Comment by mingxuan-li-official** [comment]
这是我用GPT写的插件代码
`from pathlib import Path

import nonebot
from nonebot import get_driver
from nonebot.plugin import PluginMetadata
from nonebot.typing import T_State

from .config import Config
import os
import time
from nonebot import get_bot

__plugin_meta__ = PluginMetadata(
    name="first",
    description="发送通知给管理员",
    usage="学生端->管理员",
    config=Config,
)

global_config = get_driver().config
config = Config.parse_obj(global_config)

sub_plugins = nonebot.load_plugins(
    str(Path(__file__).parent.joinpath("plugins").resolve())
)

@nonebot.on_startup
async def startup_handler():
    filename =  ''# 指定要读取的文本文件名
    qq_number = ''  # 指定要发送的QQ号

    # 获取文件的初始大小
    file_size = os.path.getsize(filename)

    while True:
        current_size = os.path.getsize(filename)

        if current_size > file_size:  # 文件有新增内容
            with open(filename, 'r', encoding='utf-8') as file:
                file.seek(file_size)  # 将文件指针定位到上次读取的位置
                new_content = file.read()  # 读取新增的内容
                #print("新增内容为:")
                #print(new_content)

            bot = get_bot()
            await bot.call_api('send_private_msg', user_id=qq_number, message=new_content)

            file_size = current_size  # 更新文件大小

        time.sleep(1)  # 每秒检查一次文件是否有新增内容

@nonebot.on_shutdown
async def shutdown_handler():
    # 在插件关闭时执行清理操作
    pass
`

**Comment by he0119** [comment]
> 不是消息时间，准确的说是监听本地的txt文件，然后将更新内容转发给指定用户，目前监听已经实现了，但是写成插件转发一直不行，希望大佬指点

转发其实就是主动发送呀。<https://github.com/he0119/nonebot2-cookbook/blob/master/docs/message/send_message_in_schedule.md>

**Comment by mingxuan-li-official** [comment]
您给的链接好像是定时发送的，如果单纯是发送有这种函数吗，或者是有条件触发发送的函数

>

**Comment by he0119** [comment]
> 您给的链接好像是定时发送的，如果单纯是发送有这种函数吗

只要 nonebot init 并且有 bot 连接后，都可以通过 get_bot 获取到 bot 并调用函数发送消息。

**Comment by mingxuan-li-official** [comment]
好的，解决了，谢谢大佬
